project:
  title: "ASL Bloom Survey Data"
  type: datapage

website:
  navbar:
    logo: images/logo.png

format:
  datapage-html:
    theme: theme.scss

execute: 
  echo: false
  message: false
  warning: false
  error: false

redivis:
  user: erinecampbell
  dataset: ASLBloomSurveyData
  table: ParentLevelData
